### ISSUE TITLE
Рома умеет выдавать GameStage

### ISSUE THREAD

**Issue by Roma444ka** [Dimas-Studio/Dimas-Adventures#14]
Андрей сказал что так не должно быть

**Comment by Roma444ka** [comment]
я это делал с помощью команды /kubejs stages add <ник> <название стадии>

**Comment by Andrey-66** [comment]
Решили пока забить

**Comment by Andrey-66** [comment]
Попробовать ftbrangs

**Comment by Andrey-66** [comment]
@Niketats
