### ISSUE TITLE
Оловянный блок

### ISSUE THREAD

**Issue by Roma444ka** [Dimas-Studio/Dimas-Adventures#2]
Оловянный блок из Mekanism не хочет подниматься, и в то же время не конвернируется 
 в блок из другого мода
![Снимок экрана от 2023-10-22 11-12-53](https://github.com/Dimas-Studio/Dimas-Adventures/assets/147881218/046fe2ba-8954-4171-a14c-dd66e5ae476d)

**Comment by Andrey-66** [comment]
@Niketats

**Comment by Andrey-66** [comment]
Добавили автоконвертацию
