### ISSUE TITLE
Квест "Но у меня не шесть глаз!" не верен

### ISSUE THREAD

**Issue by Roma444ka** [Dimas-Studio/Dimas-Adventures#22]
![2023-12-02_18 22 40](https://github.com/Dimas-Studio/Dimas-Adventures/assets/147881218/e9f460f7-acba-4a0c-9683-52453e6e203d)
Зажим для линз нужен для пистолета, а не для распространителя

**Comment by Andrey-66** [comment]
Нужно поменять описание + зависимость от излучателя маны
